---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
      communicator: winrm
      customize:
        cpus: 2
        memory: 2048
#      require_chef_omnibus: 12.18.31
      vm_hostname: false
    transport:
      name: winrm
      connection_retries: 10
      connection_retriy_sleep: 2

suites:
  - name: sphinx
    run_list:
    attributes:
      dev_mode: true
